### ISSUE TITLE
Inline mindmap sizing

### ISSUE THREAD

**Issue by lingyuanhub** [xhuajin/obsidian-mindmap-block#1]
该插件与obsidian-mindmap-nextgen其中一项功能相同，且有一样的问题就是代码块长度不可调整，当思维导图内容较多时，其文字将变得很小。不知道作者有没有办法使得代码块长度变得可调整

**Comment by xhuajin** [comment]
增加了一个可以自定义高度的选项

```mindmap
---
height: 400
---
contents
```
