### ISSUE TITLE
阅读视图切换回编辑视图后，代码块消失

### ISSUE THREAD

**Issue by lingyuanhub** [xhuajin/obsidian-mindmap-block#2]
阅读视图切换回编辑视图后，代码块消失

**Comment by xhuajin** [comment]
感谢你的bug提交，已修复

![PixPin_2024-04-10_13-38-55](https://github.com/xhuajin/obsidian-mindmap-block/assets/114134574/8ffdece5-05fa-470c-a1e1-889478b0dfad)
