### ISSUE TITLE
调整代码块高度不起作用

### ISSUE THREAD

**Issue by lingyuanhub** [xhuajin/obsidian-mindmap-block#3]
![image](https://github.com/xhuajin/obsidian-mindmap-block/assets/166458033/8008a04b-05ac-41e2-8812-fc153c03dcd1)
新库测试该插件，上图为源码，但仍无法实现调整代码块高度，可以详细说明一下吗
下图为测试结果
![image](https://github.com/xhuajin/obsidian-mindmap-block/assets/166458033/9ba9e4cb-bd64-409d-a5ae-d4db2e053b23)

**Comment by xhuajin** [comment]
高度放在代码块里面
````
```mindmap
---
height: 300
---

...
```
````

**Comment by lingyuanhub** [comment]
![image](https://github.com/xhuajin/obsidian-mindmap-block/assets/166458033/a6cce39c-5512-48c3-9480-eebd7642cdee)

依旧不成功，可能是我的问题。OB最新版1.5.12，测试库无主题，无其他插件
非常喜欢这个插件，但其高度问题令我难以受用

**Comment by xhuajin** [comment]
在release下载新版本试试，可能是我忘了传上release了，我又传了一份1.0.1

**Comment by lingyuanhub** [comment]
![image](https://github.com/xhuajin/obsidian-mindmap-block/assets/166458033/b33f3924-2ed7-4453-abf8-6df2bb38a6ae)
成功了，非常感谢分享与解答
